[package]
name = "evoid"
version = "0.1.0"
edition = "2021"

[dependencies]
macroquad = { version = "0.4", features = ["glam-serde"] }
stecs = "0.1"
raylite = "0.1"
walkdir = "2.5"
ahash = "0.8"
futures = "0.3"

kira = "0.9.*"
imageproc = { version = "0.25.*", default-features = false }
image = { version = "0.25.*", default-features = false, features = ["png", "webp"] }
fast_image_resize = { version = "5.0.*", features = ["image"] }

rhai = { version = "1.19", features = ["f32_float", "sync"] }
serde = { version = "1.0", features = ["derive"] }
ron = "0.8"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
codegen-units = 1
opt-level = 3