[package]
name = "ethervoid"
version = "0.1.0"
edition = "2021"

[dependencies]
macroquad = "0.4"
serde_json = "1.0"
raylite = "0.1.7"
image = "0.25.4"
rhai = { version = "1.19.0", features = ["f32_float", "sync"] }
