[package]
name = "ethervoid"
version = "0.1.0"
edition = "2021"

[dependencies]
macroquad = "0.4"
raylite = "0.1.7"
imageproc = "0.25.0"

ron = "0.8.*"
serde = { version = "1.0", features = ["derive"] }
rhai = { version = "1.19.0", features = ["f32_float", "sync"] }
