[package]
name = "ethervoid"
version = "0.1.0"
edition = "2021"

[dependencies]
macroquad = { version = "0.4", features = ["glam-serde"] }
kira = "0.9.*"
stecs = "0.1.*"
once_cell = "1.20.*"
walkdir = "2.5.*"
ahash = "0.8.*"
raylite = "0.1.7"
futures = "0.3.*"

imageproc = "0.25.*"
fast_image_resize = { version = "5.0.*", features = ["image"] }

rhai = { version = "1.19.0", features = ["f32_float", "sync"] }
serde = { version = "1.0", features = ["derive"] }
ron = "0.8.*"

[profile.dev.package."*"]
opt-level = 3

# TODO: Test to see if these actually improve performance
[profile.release]
codegen-units = 1
lto = "fat"
