[package]
name = "ethervoid"
version = "0.1.0"
edition = "2021"

[dependencies]
macroquad = { version = "0.4", features = ["glam-serde"] }
once_cell = "1.20.*"
walkdir = "2.5.*"
ahash = "0.8.*"
raylite = "0.1.7"
futures = "0.3.*"
glam = "*"

imageproc = { version = "0.25.*", default-features = false }
image = { version = "0.25.*", default-features = false, features = ["png", "webp"] }

rhai = { version = "1.19.0", features = ["f32_float", "sync"] }
serde = { version = "1.0", features = ["derive"] }
ron = "0.8.*"

[features]
glam-serde = ["glam/serde"]

[profile.dev.package."*"]
opt-level = 3