[package]
name = "evoid"
version = "0.1.0"
edition = "2021"

[dependencies]
macroquad = { version = "0.4", features = ["glam-serde"] }
stecs = "0.1.*"

serde = { version = "1.0", features = ["derive"] }
ron = "0.8.*"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
codegen-units = 1
opt-level = 3